### ISSUE TITLE
[Feature] Server side Pagination

### ISSUE THREAD

**Issue by abhijeetnishal** [abhijeetnishal/Password-Shield#1]
- Implement pagination (server side) 
- Limit should be dynamic with default value of 10
- Request URL should looks like: api/get?limit=10
- Response should return an object with data and data_count

**Comment by SumitKumar-17** [comment]
@abhijeetnishal I would like to work on this issue .Could you assign it to me under GSSOC'24

**Comment by Tushtiadlakha** [comment]
@abhijeetnishal  Please assign this issue to me under gssoc'24 @Tushtiadlakha. i have already worked on it

**Comment by abhijeetnishal** [comment]
Hey @SumitKumar-17, Assigning this issue to you. Good luck

**Comment by abhijeetnishal** [comment]
> @abhijeetnishal Please assign this issue to me under gssoc'24 @Tushtiadlakha. i have already worked on it

Hey @Tushtiadlakha, this issue is asked by @SumitKumar-17, so contribute to other issues.

**Comment by abhijeetnishal** [comment]
Hey @SumitKumar-17, are you working on this issue?
What's the progress?

**Comment by SumitKumar-17** [comment]
@abhijeetnishal  I am receiving some errors while ding this.
I think  it will take more time time from me.

I suppose I have wasted a lot of time. Please reassign the task to someone else.I think that will be much better.

**Comment by amanjaiswal7236** [comment]
Hey @abhijeetnishal, I would like to work on this so please assign to to me..

**Comment by abhijeetnishal** [comment]
Assigning this issue to you now.

**Comment by abhijeetnishal** [comment]
Hey @amanjaiswal7236, I have implemented this issue as it's taking more time than expected and no contributers are there back then also client side pagination is also going on.
