### ISSUE TITLE
Want to ADD Forgot Password Feature

### ISSUE THREAD

**Issue by nishant0708** [abhijeetnishal/Password-Shield#101]
**Is your feature request related to a problem? Please describe.**
Currently these is nothing for user if he forgots  his key safe password

**Describe the solution you'd like**
so in this what we can do is we will send reset password link to user when user click on that link he could reset his password

**Describe alternatives you've considered**
Instead of reseting Password we can directly send password to him through mail.(But this should only be done when user has verified his email)

**Comment by abhijeetnishal** [comment]
There is an issue #45 for this. 
Contribute to other issues good luck.
