### ISSUE TITLE
[Feat] Redesign dashboard and profile page 

### ISSUE THREAD

**Issue by abhijeetnishal** [abhijeetnishal/Password-Shield#104]
Complete redesign of dashboard page with a basic profile page.

**Comment by abhijeetnishal** [comment]
This issue is reference of issue #70

**Comment by Vimall03** [comment]
Hey @abhijeetnishal 
Kindly assign me this issue

**Comment by Vimall03** [comment]
@abhijeetnishal 
I have resolved all conflicts and successfully executed `npm run build`, addressing the errors that were encountered during the process. Despite my best efforts, I was unable to fully connect with the backend.

Given the circumstances, this is the best update I could provide. 

Kindly merge this PR if everything works well.
