### ISSUE TITLE
Add hover color to login button

### ISSUE THREAD

**Issue by AkhilaSunesh** [abhijeetnishal/Password-Shield#106]
**Describe the bug**
Add hover color to login button

**Expected behavior**
more professional

**Screenshots**
![image](https://github.com/abhijeetnishal/Password-Shield/assets/140897461/7873aecb-96d9-4b84-bff8-5da3639c6024)

**Additional context**
Kindly assign me this issue

**Comment by abhijeetnishal** [comment]
Hey @AkhilaSunesh, we are completing redesigning the UI after this it will be fixed.
