### ISSUE TITLE
Create Forgot password form

### ISSUE THREAD

**Issue by AkhilaSunesh** [abhijeetnishal/Password-Shield#107]
**Is your feature request related to a problem? Please describe.**
If a user Forgets the password it will be difficule to retrieve the password.
![image](https://github.com/abhijeetnishal/Password-Shield/assets/140897461/56ed86fd-f7be-4699-8cfb-e8023018410d)

**Describe the solution you'd like**
Add a Forgot password form

**Additional context**
Kindly assign this issue to me

**Comment by abhijeetnishal** [comment]
There is an issue #45 for this 

Contribute to other issues good luck.
