### ISSUE TITLE
Adding a favicon

### ISSUE THREAD

**Issue by Amruta7203** [abhijeetnishal/Password-Shield#109]
**Is your feature request related to a problem? Please describe.**
Adding a favicon to the website for visual appeal.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Amruta7203** [comment]
Hello @abhijeetnishal Pls assign me this issue under gssoc 24

**Comment by abhijeetnishal** [comment]
Hey @Amruta7203, this issue is resolved now as we redesigned our website.

Contribute to other issues, good luck.
