### ISSUE TITLE
Enhancing Login page 

### ISSUE THREAD

**Issue by Amruta7203** [abhijeetnishal/Password-Shield#110]
**Is your feature request related to a problem? Please describe.**
Enhancing the login page with hover effects and font style 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kushagrasaxena061** [comment]
@Amruta7203 Please assign this issue to me

 I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue

**Comment by Amruta7203** [comment]
Hello @abhijeetnishal Pls assign me this issue under gssoc 24

**Comment by abhijeetnishal** [comment]
Hey @Amruta7203, this issue is resolved now as we redesigned our website.

Contribute to other issues, good luck.
