### ISSUE TITLE
Hovering Effect in the submit button . 

### ISSUE THREAD

**Issue by namandude** [abhijeetnishal/Password-Shield#113]
Hey!! 
I would like to add the hovering effect in the  submit button appears at the time of log in  .
![Screenshot 2024-06-05 231755](https://github.com/abhijeetnishal/Password-Shield/assets/118013565/e403c218-b9e5-4db7-b29e-4bd391c89d66)

I will add up the beautiful hover effect so that it looks more appealing.

Thank You !! Please assign me this under gssoc so that i can start working on it immediatley.

**Comment by abhijeetnishal** [comment]
Hey @namandude, this issue is resolved now as we redesigned our website.

Contribute to other issues, good luck.
