### ISSUE TITLE
Hovering effect in login , add new  , get started .

### ISSUE THREAD

**Issue by namandude** [abhijeetnishal/Password-Shield#114]
Hey!! 
I would like to add the hovering effect in the  many buttons like the first and foremost the get started button so that it looks more appealing and professional , login log out button , add new button .
Here:
![Screenshot 2024-06-05 231735](https://github.com/abhijeetnishal/Password-Shield/assets/118013565/aa85e87d-a59f-4b91-823f-29c160cf14ac)
Here:
![Screenshot 2024-06-05 231917](https://github.com/abhijeetnishal/Password-Shield/assets/118013565/f0af13a8-37b5-4750-bb72-704f5c7b11b6)
Here:
![image](https://github.com/abhijeetnishal/Password-Shield/assets/118013565/4a4d81c0-31f0-4fa9-8d86-dc65b9b4f524)

I will add up the beautiful hover effect so that it looks more appealing.

Thank You !! Please assign me this under gssoc so that i can start working on it immediatley.

**Comment by abhijeetnishal** [comment]
Hey @namandude, this issue is resolved now as we redesigned our website.

Contribute to other issues, good luck.
