### ISSUE TITLE
Editing the contribution.md file.

### ISSUE THREAD

**Issue by pranavc13** [abhijeetnishal/Password-Shield#116]
I am interested in contributing to the project by editing the Contribution.md file by adding new guidelines and process such as:

Giving detailed description of Github desktop
Providing links for learning basics of Github
Pull Request process;
Community Guidelines
Code Reviews etc 

By providing clear and comprehensive guidnce, we can encourage more contributors to participate in the project.
Our contributions.md file could me made more attractive and bring the interest of different people.

Could you please assign me the project under GSSOC'24?

**Comment by abhijeetnishal** [comment]
Hey @pranavc13, all the required details are already present.

Contribute to other issues, good luck.
