### ISSUE TITLE
Password strength and toggle password visibility

### ISSUE THREAD

**Issue by agarwalhimanshugaya** [abhijeetnishal/Password-Shield#118]
**Is your feature request related to a problem? Please describe.**
1.Your website store password but your website take any password from user which is bad you have to make the feature so that user get  suggestion when he type simple password 
2.your website have not feature of see the password due to which user face difficulty when he type some wrong letter

**Describe the solution you'd like**
your website should give suggestion to user when he type simple password and also we can give one eye button in password box so that user can toggle the password visiblity
kindly assign me this issue under Gssoc'24

**Describe alternatives you've considered**

**Additional context**

**Comment by abhijeetnishal** [comment]
Hey @agarwalhimanshugaya, this issue is resolved now as we redesigned our website.

Contribute to other issues, good luck.
