### ISSUE TITLE
Can add a customized logo.

### ISSUE THREAD

**Issue by sweta-singh28** [abhijeetnishal/Password-Shield#123]
*Is your feature request related to a problem? Please describe.*
Yes, can add a logo to the project. Without a logo, the project lacks a visual identity, making it appear less professional and cohesive.

*Describe the solution you'd like*
I would like to integrate a logo into the project. This should include:
Displaying the logo on the homepage and in the main header.

*Describe alternatives you've considered*
Creating a simple logo.
Using an open-source logo that loosely represents the project.

*Additional context*
The logo should be in SVG format for scalability and should have versions that work on both dark and light backgrounds.

**Comment by abhijeetnishal** [comment]
Hey @sweta-singh28, you are thinking of adding custom logo wrt to passwords right? 
Could you explain how many custom logo are you planning to add and how do give users to add custom password?

**Comment by sweta-singh28** [comment]
No sir I'm thinking of adding a logo to the project i.e. designing and adding a logo to the project password shield.

**Comment by abhijeetnishal** [comment]
Hey @sweta-singh28, I think we already have logo, earlier it was there, may be after redesigning it is not showing. I will fix that.

Contribute to other issues, good luck.
