### ISSUE TITLE
Add dynamic year code in footer section

### ISSUE THREAD

**Issue by arpit4521** [abhijeetnishal/Password-Shield#127]
![Screenshot 2024-06-11 212147](https://github.com/abhijeetnishal/Password-Shield/assets/127679958/a1f1cd08-1088-4cc0-bbe7-9c7da23cb36f)

**Comment by arpit4521** [comment]
@abhijeetnishal please assign me this under gssoc label and apt level

**Comment by abhijeetnishal** [comment]
Hey @arpit4521, this is currently not relevant and important for users. Contribute to other issues, good luck.
