### ISSUE TITLE
Add transition

### ISSUE THREAD

**Issue by K-kiran77** [abhijeetnishal/Password-Shield#128]
**Is your feature request related to a problem? Please describe.**
When switching from dark mode to light mode the theme changes suddenly

**Describe the solution you'd like**
I would like to add transition when switching from dark mode light mode and vice versa which enhances the user experience

**Describe alternatives you've considered**

**Additional context**

**Comment by abhijeetnishal** [comment]
Hey @K-kiran77, Currently we don't need transition or animation for this project as there are lot of features that needs to be done.

Contribute to other issues, good luck.
