### ISSUE TITLE
Add Navigation links in register and Login page

### ISSUE THREAD

**Issue by divyansh-2005** [abhijeetnishal/Password-Shield#129]
**Is your feature request related to a problem? Please describe.**
Navigation links to Home, About, Contact can de added in register and Login page.

**Describe the solution you'd like**
I want to add links on register and login page

**Describe alternatives you've considered**

**Additional context**

**Comment by abhijeetnishal** [comment]
Hey @divyansh-2005, users can redirect to home on clicking the logo button as navigation is in single page that's why. 

Contribute to other issues, good luck.
