### ISSUE TITLE
[Feature Request]: Add Feedback/Contact form

### ISSUE THREAD

**Issue by divyansh-2005** [abhijeetnishal/Password-Shield#130]
**Is your feature request related to a problem? Please describe.**
A feedback/contact form can be added under contact section of website

**Describe the solution you'd like**
I would add a simple form to the contact section.

**Comment by abhijeetnishal** [comment]
Hey @divyansh-2005, currently we have added the contact info like github and linkedin. We don't need contact form now. 

Contribute to other issues, good luck.
