### ISSUE TITLE
Add provision to view password

### ISSUE THREAD

**Issue by AkhilaSunesh** [abhijeetnishal/Password-Shield#131]
**Is your feature request related to a problem? Please describe.**
The user cannot verify whether the password he/she has typed in the login and signup page.

**Describe the solution you'd like**
Add the show password feature

**Additional context**
![image](https://github.com/abhijeetnishal/Password-Shield/assets/140897461/a24db7e1-6113-42c3-a1e4-ec2c9c938b1a)
Kindly assign this issue to me

**Comment by abhijeetnishal** [comment]
This will be fixed, Contribute to other issues.
