### ISSUE TITLE
Incorrect icon

### ISSUE THREAD

**Issue by AkhilaSunesh** [abhijeetnishal/Password-Shield#132]
**Describe the bug**
In the features section: the icon for "unmatched security" should be replaced with a shield.

**Expected behavior**
more clear understanding

**Screenshots**
![image](https://github.com/abhijeetnishal/Password-Shield/assets/140897461/5ef8768e-a03e-4b82-82e2-5d7320ba091b)

**Additional context**
Kindly assign this issue to me

**Comment by abhijeetnishal** [comment]
Hey @AkhilaSunesh, this is not a bug it just a icon issue. It will be fixed later with other issue.

Contribute to other issues, good luck.
