### ISSUE TITLE
[FEAT]: Add "Remember Me" Section for Auth 

### ISSUE THREAD

**Issue by codercake** [abhijeetnishal/Password-Shield#134]
I**s your feature request related to a problem? Please describe.**
Repeatedly logging in with username and password can be quite time-consuming.

**Describe the solution you'd like**
The “Remember Me” feature for authentication is designed to improve user experience by reducing the frequency of login prompts. When a user selects “Remember Me” during login, the system stores a persistent cookie in the user’s browser. This cookie allows the system to recognize the user’s device and browser for a set period, typically ranging from several days to a few months.

**Screenshots** 
![Screenshot 2024-06-15 123245](https://github.com/abhijeetnishal/Password-Shield/assets/117517206/cf1da160-118f-4d06-8b45-f38dd60b4c31)

**Comment by abhijeetnishal** [comment]
Currently we already have much token expiry time so we don't need this. Also nowadays remen
