### ISSUE TITLE
New Features Requested 

### ISSUE THREAD

**Issue by Samrudhi00** [abhijeetnishal/Password-Shield#136]
**### Assign me this issue for GSSoC'24**

**1) Login with Google**
**Is your feature request related to a problem? Please describe.**
Managing multiple passwords for different applications is frustrating. It would be convenient to log in using an existing Google account.

**Describe the solution you'd like**
Integrate Google Login via OAuth 2.0, allowing users to authenticate with their Google accounts.

**Describe alternatives you've considered**
Allowing login with other social media accounts like Facebook or Twitter.

**2) Enhance the UI and Add Search Bar**
**Is your feature request related to a problem? Please describe.**
Finding specific passwords in a long list is time-consuming, and the current UI could be more user-friendly.

**Describe the solution you'd like**
Improve the UI using  CSS for a modern look and add a search bar to quickly find password entries.

![Screenshot (991)](https://github.com/abhijeetnishal/Password-Shield/assets/89694069/312f775e-8184-4985-a7fd-8d1bfa2c7908)

**3) Fixed Header**
**Is your feature request related to a problem? Please describe.**
Scrolling back to the top to access navigation is inconvenient.

**Describe the solution you'd like**
Implement a fixed header that remains visible as the user scrolls, containing main navigation and key actions.

![Screenshot (992)](https://github.com/abhijeetnishal/Password-Shield/assets/89694069/c9b2fd64-0a5e-45f7-ae28-12ad19ecbce1)

**Comment by abhijeetnishal** [comment]
This feature is already there, see issue #93 

Closing this issue as duplicate
