### ISSUE TITLE
BUG 🐞: Dark mode gets turned off on refreshing a page

### ISSUE THREAD

**Issue by Tejashri-Taral** [abhijeetnishal/Password-Shield#137]
Hey @abhijeetnishal ,
Here is the issue I encountered -
The dark mode preference does not persist across page refreshes. Each time the page is refreshed, the mode resets to the default instead of maintaining the user-selected mode (dark or light).
I think it is due to the theme state is not being persisted when the page is refreshed.

****To Reproduce****

Go to the website.
Toggle the light mode switch to change the theme.
Refresh the page.
Observe that the theme reverts to the default mode instead of retaining the selected mode.

****Expected behavior****
The selected dark or light mode should persist across page refreshes.
If a user selects dark mode, the page should remain in light mode even after refreshing.

******Screenshots (Mandatory)******

Before refreshing the page looks like (currently in dark mode):

![image](https://github.com/abhijeetnishal/Password-Shield/assets/160386036/7eddfd43-0de2-44e7-b925-54bd8d81f1b1)

After refreshing the page:

![image](https://github.com/abhijeetnishal/Password-Shield/assets/160386036/e959b61e-21a6-4c8d-ac92-9712491d03f2)

**Are you contributing under any open-source program?**
GSSOC'24

I hope I was able to explain the issue and the expected solution.
If so, Could you please assign this issue to me under GSSoC 24?

**Comment by Charul00** [comment]
i want to contribute for this bug
