### ISSUE TITLE
Forget password implementation

### ISSUE THREAD

**Issue by mukilan2815** [abhijeetnishal/Password-Shield#138]
**Is your feature request related to a problem? Please describe.**
Adding Forge password in this website

**Describe the solution you'd like**
If user clicks that it will snd otp to the email and if he enters it correctly he can modif the password.

**Additional context**
Please assign under GSSOC'24 level 3 as it is backend

**Comment by abhijeetnishal** [comment]
Hey @mukilan2815, this feature is already implemented. It will be live in some days.

Contribute to other issues, good luck.
