### ISSUE TITLE
Chatbot for answering user queries 

### ISSUE THREAD

**Issue by Astha86** [abhijeetnishal/Password-Shield#139]
**Is your feature request related to a problem? Please describe.**
A Chatbot can be deployed for answering any user Queries

**Describe the solution you'd like**
Deploying a Chatbot on website that will be enhance the user experience.

**Additional context**
@abhijeetnishal Kindly assign me this issue under GSSOC'24

**Comment by abhijeetnishal** [comment]
Hey @Astha86, currently we don't have much features to add chatbot feature, may be in future we will add. 

Contribute to other issues, good luck.
