### ISSUE TITLE
Stop navbar at top

### ISSUE THREAD

**Issue by Rajput-xv** [abhijeetnishal/Password-Shield#140]
While scrolling through the web page the navbar seems to be hidden and user can't navigate to other pages through navbar unless he goes back to top.
so, i would like to work on this issue.

@abhijeetnishal 
kindly assign this issue to me.

**Comment by abhijeetnishal** [comment]
Hey @Rajput-xv, currently our home page is not that much long to implement this. Contribute to other issues, good luck.
