### ISSUE TITLE
Enhancing home page 

### ISSUE THREAD

**Issue by driyash9881** [abhijeetnishal/Password-Shield#142]
# Enhancing the Home Page

## Before
![Before Home Page](https://github.com/abhijeetnishal/Password-Shield/assets/118407844/32818289-01c9-4a4a-b79a-5aff7b465f7a)

## After
![After Home Page](https://github.com/abhijeetnishal/Password-Shield/assets/118407844/44b1715f-6c4c-438c-9d2d-100759333a38)

### On Hover
![Home Page on Hover](https://github.com/abhijeetnishal/Password-Shield/assets/118407844/c2418b2e-3f60-436a-8b71-f71db76e46db)

## Before Login/Register Screen
![Before Login/Register Screen](https://github.com/abhijeetnishal/Password-Shield/assets/118407844/72a9fa63-de11-4832-a9ee-5532319e9218)

## After Adding Home and Changing the Night Icon
![After Login/Register Screen](https://github.com/abhijeetnishal/Password-Shield/assets/118407844/5b2708da-4e01-4542-89f4-5f1ae6fb8432)

## Before Contact Us Card
![Before Contact Us Card](https://github.com/abhijeetnishal/Password-Shield/assets/118407844/63ca8fcb-f48c-4203-acb9-e82d2ecf063a)

## After Applying Changes to Contact Us Card
![After Contact Us Card](https://github.com/abhijeetnishal/Password-Shield/assets/118407844/4d8acf5b-6f84-466e-8412-10417dea8f5a)
![Contact Us Card Close-up](https://github.com/abhijeetnishal/Password-Shield/assets/118407844/611b191b-9f77-4f89-99fa-14985b066a5b)

**Comment by abhijeetnishal** [comment]
Hey @driyash9881, current design is fine for now. Contribute to other issues, good luck.
