### ISSUE TITLE
Prelaoder

### ISSUE THREAD

**Issue by Jagpreet153** [abhijeetnishal/Password-Shield#144]
**Is your feature request related to a problem? Please describe.**
Yes , it will increase user interest in the website

**Describe the solution you'd like**
I will add simple animation that will render until the page is being loaded 

**Describe alternatives you've considered**
The preloader will be completely responsive and matching the theme of project

**Additional context**
Kindly assign this issue to me under GSSoC'24

**Comment by abhijeetnishal** [comment]
Hey @Jagpreet153, this feature is not required. Contribute to other issues good luck.
