### ISSUE TITLE
Attractive logo for website

### ISSUE THREAD

**Issue by vaishnavip27** [abhijeetnishal/Password-Shield#145]
As we know, how much a logo plays an important role in the website'sUI. I want to design an attractive logo for your website.
please @abhijeetnishal assign me this issue

**Comment by abhijeetnishal** [comment]
Hey @vaishnavip27, do you have any logo?

**Comment by Khushi-Pushkar** [comment]
@abhijeetnishal please assign this issue to me

**Comment by Khushi-Pushkar** [comment]
![Screenshot 2024-06-25 234809](https://github.com/abhijeetnishal/Password-Shield/assets/142687709/5e893dbc-0cb6-4d19-b972-d73521cbc7c2)
![Screenshot 2024-06-25 234935](https://github.com/abhijeetnishal/Password-Shield/assets/142687709/34bbb570-46ef-4335-a4d1-6ae860a0a159)
![Screenshot 2024-06-25 235844](https://github.com/abhijeetnishal/Password-Shield/assets/142687709/4424ac9e-294b-467f-80ec-98faf4d32ea3)
![image](https://github.com/abhijeetnishal/Password-Shield/assets/142687709/72bb919f-56b4-4a80-b1f4-6e56d59ef058)

**Comment by Khushi-Pushkar** [comment]
@abhijeetnishal Do you like any of the logos? Or should I create more logos for you?

**Comment by abhijeetnishal** [comment]
Hey @Khushi-Pushkar, these logo's not looking promising. I will look for better logo. 

Why don't you work for other issues like we have to redesign dashboard UI.
