### ISSUE TITLE
Add logo

### ISSUE THREAD

**Issue by Khushi-Pushkar** [abhijeetnishal/Password-Shield#148]
Hey @Abhinavhaldiya @abhijeetnishal  . I am a GSSoC'24 Contributor.

I'd like to contribute to your project by create a logo for your website and add to it
Kindly assign this issue to me.

**Comment by Khushi-Pushkar** [comment]
But she has not completed it yet. Give a chance, I will complete it by tomorrow. @abhijeetnishal

**Comment by abhijeetnishal** [comment]
> But she has not completed it yet. Give a chance, I will complete it by tomorrow. @abhijeetnishal

Hey @Khushi-Pushkar, ask on that issue and share the possible logo I will assign it to you.
