### ISSUE TITLE
Website Missing Logo & Favicon

### ISSUE THREAD

**Issue by ansh-h-mehta** [abhijeetnishal/Password-Shield#150]
**Is your feature request related to a problem? Please describe.**
A logo and Favicon will enhance the overall look of the website & build trust among the users

**Describe the solution you'd like**
Implementation of a Favicon

**Describe alternatives you've considered**
Creating a good Logo

**Additional context**
![image](https://github.com/abhijeetnishal/Password-Shield/assets/99081110/4d17d477-b584-454e-a896-4ed649b025a7)

**Comment by abhijeetnishal** [comment]
Currently the name is itself the logo. Closing this issue, contribute to other issues.
