### ISSUE TITLE
Redirecting About & Contact

### ISSUE THREAD

**Issue by n-keerthi-gayathri** [abhijeetnishal/Password-Shield#151]
**Describe the bug**
About & Contact in Footer of Register & Login Page are not redirecting to corresponding links.

**Screenshots**
![image](https://github.com/abhijeetnishal/Password-Shield/assets/118381441/7da23429-fddd-4327-85bf-23c65917b3f2)

**Comment by n-keerthi-gayathri** [comment]
@abhijeetnishal please assign me this under GSSOC'24

**Comment by abhijeetnishal** [comment]
The redirection is not possible as there is a single for all routes and using react-scroll. Contribute to other issues.
