### ISSUE TITLE
Revamp about and contact page

### ISSUE THREAD

**Issue by Ojas-Arora** [abhijeetnishal/Password-Shield#153]
**Is your feature request related to a problem? Please describe.**
 @abhijeetnishal I want to make changes to the about and contact page to make them better . Kindly assign this issue to me.

**Describe the solution you'd like**
NA

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by abhijeetnishal** [comment]
Hey @Ojas-Arora, the about and contact is in home page only, contribute to other issues, good luck.
