### ISSUE TITLE
Register button not needed 

### ISSUE THREAD

**Issue by Ojas-Arora** [abhijeetnishal/Password-Shield#154]
**Describe the bug**
@abhijeetnishal There is already a login button in the page so there is no requiremnet of register button. Kindly assign this issue to me.

**To Reproduce**

**Expected behavior**
NA

**Screenshots**
NA

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
NA

**Comment by abhijeetnishal** [comment]
Hey @Ojas-Arora, for now the UI looks fine, contribute to other issues, good luck.
