### ISSUE TITLE
Changes in footer section

### ISSUE THREAD

**Issue by Ojas-Arora** [abhijeetnishal/Password-Shield#155]
**Is your feature request related to a problem? Please describe.**
@abhijeetnishal I want to add more features to footer section. Kindly assign this issue to me.

**Describe the solution you'd like**
NA

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by abhijeetnishal** [comment]
Hey @Ojas-Arora, footer section is not as important to add hover, contribute to other issues.
