### ISSUE TITLE
Zoom in & out effect of cards

### ISSUE THREAD

**Issue by Tanishashrivas** [abhijeetnishal/Password-Shield#158]
**Is your feature request related to a problem? Please describe.**
I would like to add the feature of zoom in and out on these cards:
![Screenshot 2024-07-04 152811](https://github.com/abhijeetnishal/Password-Shield/assets/114223066/8e72cdc3-5c13-4793-aeaa-925e32b857f0)

Making the website more interactive and enhanced

**Comment by Tanishashrivas** [comment]
Please assign it to me under gssoc

**Comment by abhijeetnishal** [comment]
Currently this feature is not required. Contribute to other issues.
