### ISSUE TITLE
Scroll to the top button

### ISSUE THREAD

**Issue by Tanishashrivas** [abhijeetnishal/Password-Shield#159]
**Is your feature request related to a problem? Please describe.**
Scroll to the top button

**Describe the solution you'd like**
When clicked, this will take the user back to the top of the page

**Comment by skushagra** [comment]
I would like to contribute to this issue.

**Comment by skushagra** [comment]
I have raised a PR for this. If possible someone can review it!

**Comment by abhijeetnishal** [comment]
Hey @Tanishashrivas and @skushagra, the landing page is not that much long so we don't need this button. Contribute to other issues, go to the issues to see.
