### ISSUE TITLE
[Enhancement] Connect to Database only when required

### ISSUE THREAD

**Issue by abhijeetnishal** [abhijeetnishal/Password-Shield#16]
## Description:
Currently, server establishes a connection to the Postgres database as soon as the server starts. This means that the database connection is always active, even when no requests are being made to the server. This can lead to unnecessary resource usage and potential performance issues.

## Requirements:
- Modify the existing code to connect to the Postgres database only when a request is received that requires database access.
- Ensure that the database connection is closed when it is no longer needed to conserve resources.
- Implement a mechanism to handle errors that may occur when connecting to the database lazily.
  
## Technical Details:
- Server is built using Node.js and Express.js as the backend framework.
- This project is using PostgreSQL as our database.
- The current implementation establishes a connection to the PostgreSQL database using the pg library in the server startup code.

## Example Scenario:
- When the server starts, no database connection is established.
- When a request is received to create a new shortened URL, the database connection is established, the URL is saved to the database, and the connection is closed.
- When a request is received to retrieve a shortened URL, the database connection is established, the URL is retrieved from the database, and the connection is closed.

### Acceptance Criteria:
- The database connection is not established when the server starts.
- The database connection is established only when a request is received that requires database access.
- The database connection is closed when it is no longer needed.
- Errors that occur during lazy loading of the database connection are handled correctly.

### Estimated Time: 
This issue is estimated to take around 1-2 days to complete, depending on the contributor's experience.

**Comment by NilanchalaPanda** [comment]
Hey @abhijeetnishal, I have worked on Backend applications with NodeJs, ExpressJs and MongoDb as their stack and would love to explore more other SQL-based databases. So can you assign this issue to me. Looking forward for your reply.

**Comment by abhijeetnishal** [comment]
Hey @NilanchalaPanda, I already assigned an issue #5. 
First try to finish this issue then i will assign this to you.
Good luck.

**Comment by NilanchalaPanda** [comment]
Sure thing, no problem @abhijeetnishal 🙌🏻

**Comment by Abhinavhaldiya** [comment]
Hey @NilanchalaPanda ,I am Abhinav contributor from GSSOC I am interested to solve this issue #16 as i previous worked on a project of postgres database and i confident enough to solve it.

**Comment by Indranil0603** [comment]
Hey @abhijeetnishal , I would like to work on the issue , i feel i have figured out the solution to use connection pooling to complete this.

**Comment by abhijeetnishal** [comment]
> Hey @abhijeetnishal ,I am Abhinav contributor from GSSOC I am interested to solve this issue #16 as i previous worked on a project of postgres database and i confident enough to solve it.

Hey @Abhinavhaldiya, I am assigning this issue, use connection polling as mentioned by @Indranil0603.

**Comment by abhijeetnishal** [comment]
> Hey @abhijeetnishal , I would like to work on the issue , i feel i have figured out the solution to use connection pooling to complete this.

Hey @Indranil0603, this issue is assigned to @Abhinavhaldiya as he asked earlier. Contribute to other issue, good luck.

**Comment by Abhinavhaldiya** [comment]
Thanks @abhijeetnishal for assigning the issue I am working on it and will try to pull the request by tomorrow.

**Comment by abhijeetnishal** [comment]
> Thanks @abhijeetnishal for assigning the issue I am working on it and will try to pull the request by tomorrow.

Great @Abhinavhaldiya
