### ISSUE TITLE
[Feature Request]: Migrate model from raw SQL to prisma

### ISSUE THREAD

**Issue by skushagra** [abhijeetnishal/Password-Shield#161]
**Problem Statement**
Currently raw SQL queries are written on  the in the models we should migrate them a Prisma schema and use the ORM to make all crud operations.

**Solution**
Migrate schema to Prisma

**Comment by abhijeetnishal** [comment]
Hey @skushagra, prisma package is soo heavy as compared to pg so its better to use this only. Contribute to other issues, good luck.
