### ISSUE TITLE
Add Email Verification for Signup and Login

### ISSUE THREAD

**Issue by Slacky300** [abhijeetnishal/Password-Shield#17]
**Proposal: Implement Email Verification System**

### Objective:
Implement an email verification system for user registration and login processes to enhance security and user experience.

### Key Features:
- **Email Verification Upon Registration:** 
  - Upon registration, the system should automatically send a verification email to the user's provided email address.

- **Login Restriction:** 
  - Until the user verifies their email address, they should not be able to log in to the platform.

- **Notification for Unverified Accounts:**
  - Users attempting to log in without verifying their email address should receive a notification indicating their account is not verified.

- **Resend Verification Email:**
  - Users should have the option to request a new verification email if they haven't received it or have accidentally deleted it.
  - This resend functionality should be easily accessible from the login screen or through the user's account settings.

### Benefits:
- **Enhanced Security:**
  - Only users with verified email addresses can access their accounts, reducing the risk of unauthorized access.

- **Improved User Experience:**
  - Providing users with the option to request a new verification email reduces frustration in case of missed or lost emails.

By implementing this feature, we aim to significantly enhance the security of the platform while improving the overall user experience.

**Comment by abhijeetnishal** [comment]
Hey @Slacky300, Could you explain the more about the design like what service you are using (google, sendgrid, etc), what verification type you are using (verification code or verification email using token) and also the flow of verification.

**Comment by Slacky300** [comment]
### Design Overview:

#### Email Service Provider:
We'll utilize **Gmail's SMTP server** to send verification emails. Gmail's SMTP server provides reliable email delivery services and integrates seamlessly with our application.

#### Verification Type:
We'll implement verification using **verification emails with tokens**. Upon user registration, a unique verification token will be generated using JWT. This token will be embedded in the verification email sent to the user's provided email address.

#### Flow of Verification:
1. **User Registration:**
   - When a user registers on the platform, their account is created in the database.
   - Alongside standard user attributes, two additional attributes, `isVerified` (boolean) and `verificationToken` (string), are added to the user model.

2. **Sending Verification Email:**
   - Upon successful registration, a verification email is sent to the user's email address using Gmail's SMTP server and Nodemailer.
   - The email contains a verification link with the JWT token embedded in the URL, enabling direct verification.

3. **Verification Endpoint:**
   - When the user clicks the verification link, they're directed to the platform's verification endpoint.
   - The endpoint verifies the token:
     - If the token is valid and has not expired, the user's `isVerified` attribute is set to `true`, confirming their email address.
     - If the token is invalid or expired, an error message is displayed, prompting the user to request a new verification email if necessary.

4. **Login Process:**
   - During login attempts, the system verifies whether the user's email address is verified (`isVerified` attribute).
   - If the email address is not verified, the user is prevented from logging in and prompted to verify their email.

5. **Resending Verification Email:**
   - Users who haven't received the initial verification email or accidentally deleted it can request a new verification email.
   - Upon request, a new verification token is generated, and the email containing the verification link is sent again.

### Conclusion:
Implementing this design ensures secure and seamless email verification for user registration and login processes, enhancing both security and user experience.

**Comment by Slacky300** [comment]
Okay I understood the approach you mentioned, I'll do it accordingly.

**Comment by abhijeetnishal** [comment]
Great @Slacky300.

**Comment by abhijeetnishal** [comment]
Hey @Slacky300, what's the progress?
If you need any help let me know

**Comment by Slacky300** [comment]
> Hey @Slacky300, what's the progress? If you need any help let me know

Hey @abhijeetnishal,
It's completed just need to make some final changes, before making the pull request. It will be fully completed by tomorrow evening, and I’ll make the pull request then.

**Comment by abhijeetnishal** [comment]
Hey @Slacky300, how's things going, did you need any help?

**Comment by RoshanAnsy** [comment]
Hey @abhijeetnishal, I read about your approach and truly understand your design pattern. Can you assign it to me?

**Comment by atharvarekhawar** [comment]
hey @abhijeetnishal I would like to work on this issue if no one is working on it.

**Comment by saurabhbakolia** [comment]
Hey @abhijeetnishal  I would like to work on this issue, I have understood the approach. 
Thanks.

**Comment by abhijeetnishal** [comment]
Hey @RoshanAnsy, are you available to work on this issue?

**Comment by RoshanAnsy** [comment]
@abhijeetnishal  yes

**Comment by abhijeetnishal** [comment]
Great @RoshanAnsy, assigning this issue to you now.

**Comment by atharvarekhawar** [comment]
hey @RoshanAnsy , are you still working on this?

**Comment by RoshanAnsy** [comment]
Almost is done currently I am doing testing of our code base.

**Comment by RoshanAnsy** [comment]
@abhijeetnishal 

hey I am at the final stage and need insure from your side 

1. First time when user Register at time we need to verify the email if it did not verify then it can not jump to next the page ?
2. second way user can register thirre account and after some it verify the email ?

let me know which one i have to implement ?

**Comment by abhijeetnishal** [comment]
Hey @RoshanAnsy, When users register then we send verification email as discussed above and after verification only it will redirect to dashboard page after creating token from server.

**Comment by saurabhbakolia** [comment]
@abhijeetnishal 
Hey! If no one is working on it, please assign this issue to me.

**Comment by abhijeetnishal** [comment]
Hey @RoshanAnsy, are you working on this? 

Also this functionality is already implemented using forget password feature that's why i changed the level, now its just need to add one page, routes and all are already implemented.

**Comment by RoshanAnsy** [comment]
I completed backend code and it is working fine but I have to changes also in frontend that's the reason it's taking time.
if anyone who want to worked on frontend part then add them also i talk to him/her about this approaches.
@abhijeetnishal

**Comment by saurabhbakolia** [comment]
> I completed backend code and it is working fine but I have to changes also in frontend that's the reason it's taking time. if anyone who want to worked on frontend part then add them also i talk to him/her about this approaches. @abhijeetnishal

I would like to work on this!

**Comment by abhijeetnishal** [comment]
Hey @RoshanAnsy, the backend part is already implemented you can use endpoints to implement frontend only. It's been a while you haven't implemented this feature and one contributer implemented the same for forget and reset password and created a PR and done the required changes for both frontend and backend within a week and I have given you more than 2 week. We can't wait as it's strict guidelines from gssoc. So just implement the frontend of you want.

**Comment by UtkarshBirla28** [comment]
@abhijeetnishal  Assign me this issue sir i will fix it ASAP

**Comment by abhijeetnishal** [comment]
Hey @UtkarshBirla28, did you get the approach what we have discussed?

**Comment by abhijeetnishal** [comment]
Closing this issue as not active.
