### ISSUE TITLE
Making buttons hover and have shadows when cursor hovers on it.

### ISSUE THREAD

**Issue by Rakshit-gen** [abhijeetnishal/Password-Shield#18]
**Is your feature request related to a problem? Please describe.**
Currently buttons are not that reactive to mouse hovering on them.

**Describe the solution you'd like**
Adding some shadow and hover effect to buttons when mouse reaches them.

**Additional context**
Please assign this issue to me I am a GSSoC 2024 contributor.

**Comment by abhijeetnishal** [comment]
Hey @Rakshit-gen, we are currently updating some UI like login/signup, once it's done you can work. Also it's easy for you also.

**Comment by Rakshit-gen** [comment]
Okay sir please tell me when I can work on it

**Comment by abhijeetnishal** [comment]
@Rakshit-gen I will let you know.

**Comment by Tanishka023** [comment]
Hey there! I am excited to contribute to this project; please assign it to me.

**Comment by abhijeetnishal** [comment]
Closing this issue as done
