### ISSUE TITLE
Adding about and footer section

### ISSUE THREAD

**Issue by agxmbedi** [abhijeetnishal/Password-Shield#19]
I am Agamjot singh. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!
<img width="1440" alt="Screenshot 2024-05-10 at 10 50 49 PM" src="https://github.com/abhijeetnishal/Password-Shield/assets/111156687/61d0c3bf-8649-446b-b002-de208a414917">

**Comment by Caliber-Ruchi** [comment]
I would like to add about and footer section .Kindly assign it  to me.

**Comment by Tanishka023** [comment]
Hey there! I am excited to contribute to this project; please assign it to me.

**Comment by abhijeetnishal** [comment]
Anyone have any reference UI you are following for changes.
Please share once to move further

**Comment by abhijeetnishal** [comment]
I am closing this issue now i guess no one is working.
