### ISSUE TITLE
[Feature] Client side Pagination

### ISSUE THREAD

**Issue by abhijeetnishal** [abhijeetnishal/Password-Shield#2]
#1 Server side implementation issue 

### Requirements:
- Share the reference UI for pagination before implementing
- Pagination is dynamic with default value of 10
- UI should be responsive

**Comment by SumitKumar-17** [comment]
@abhijeetnishal I would like to work on this issue .Could you assign it to me under GSSOC'24.

**Comment by abhijeetnishal** [comment]
Hey @SumitKumar-17, assigning this issue to you.

**Comment by Abhinavhaldiya** [comment]
Hii @abhijeetnishal  I have some ideas about the client side pagination as i have worked on it earlier.
This can be possible by using react-data-table-component and it has lot of other features like exporting data into csv file,pagination,sorting  and make rows selectable.

@SumitKumar-17 you can also take reference from there.

**Comment by abhijeetnishal** [comment]
Hey @Abhinavhaldiya, this issue is already assigned this issue to @SumitKumar-17 for now.

We don't need to use external library for pagination that's why it's level2 issue.

**Comment by SumitKumar-17** [comment]
@abhijeetnishal  I am receiving some errors while ding this.
I think  it will take more time time from me.

I suppose I have wasted a lot of time. Please reassign the task to someone else.I think that will be much better.

**Comment by Abhinavhaldiya** [comment]
> @abhijeetnishal I am receiving some errors while ding this. I think it will take more time time from me.
> 
> I suppose I have wasted a lot of time. Please reassign the task to someone else.I think that will be much better.
Hii @abhijeetnishal I had the good idea about the client side pagination but you want to implement it without using any library it would be more helpful if you just specify some of the functionalities(like we want to export the data into csv by selecting particular rows which eventually become very difficult without using the package) if i would be simple like we need to just display the data i can implement it from the scratch without using any library.

Looking forward for your response

**Comment by abhijeetnishal** [comment]
> "Hi @abhijeetnishal, I have a great idea for implementing client-side pagination, but you prefer to do it without using any library. It would be helpful if you could specify some of the functionalities. For example, exporting data to CSV by selecting particular rows, which could become quite challenging without using a package. If it were simpler, like just displaying the data, I could implement it from scratch without using any library. Could you clarify the requirements?" Looking forward for your response

Hey @Abhinavhaldiya, we don't need export option for just pagination. If you implement that then I am assigning this issue to you now.

**Comment by abhijeetnishal** [comment]
> Hey @abhijeetnishal I can work on this! I've previously implemented pagination for some of my own projects too :) I'm will work on this under GSSOC

Hey @ritu713, you can work on other issues for now I have assigned @Abhinavhaldiya. Good luck

**Comment by abhijeetnishal** [comment]
Hey @Abhinavhaldiya, create a separate component for this.

**Comment by Abhinavhaldiya** [comment]
Hii @abhijeetnishal  I have tried connecting to the database but it is not working.

Things that i have done are:
1) create .env in server
2)Replace the env variables with my own database

Is there any other step to connect the database?

**Comment by abhijeetnishal** [comment]
Have you added your postgres user, passsword, host, port, etc in the env file. It will run if PostgreSQL credentials are corrent

**Comment by abhijeetnishal** [comment]
Install pgadmin for setting up postgres

**Comment by Abhinavhaldiya** [comment]
Sir I have tried all the possible ways to connect to db but i don't know what is the issue.The request gets hung in between can just give the sample data which we will get while hitting the route view.so that i can have some idea.

**Comment by abhijeetnishal** [comment]
So you are facing connecting the database, you are using local postgres or cloud one?

**Comment by Abhinavhaldiya** [comment]
cloud one

**Comment by Abhinavhaldiya** [comment]
I had also tried the local one but it is giving some hostname error

**Comment by abhijeetnishal** [comment]
Try to match same credentials as cloud it will work as it's working for us.
Hostname should contain the address of host 
Which cloud you are using?

**Comment by Abhinavhaldiya** [comment]
okay i will try it again
