### ISSUE TITLE
You can see the password you type , can have hide/unhide button in register/login page for better user experience

### ISSUE THREAD

**Issue by Adeesh-bode** [abhijeetnishal/Password-Shield#21]
**Is your feature request related to a problem? Please describe.**
Yes, the problem is that currently, when users type their password on the register/login page, it's displayed as plaintext, which can be insecure and uncomfortable, especially in public or shared spaces. I'm always frustrated when I can't hide my password as I type, affecting my sense of privacy and security.

**Describe the solution you'd like**
I would like to have a hide/unhide button added to the password input fields on both the registration and login pages. This button would allow users to toggle the visibility of their password, helping them to confirm they've typed it correctly without compromising on privacy.

**Describe alternatives you've considered**
An alternative could be implementing a default masked password field with an option to view the password only while the mouse is clicked or held down over an eye icon. This approach is less interactive but still offers users control over password visibility.

**Additional context**
This feature is quite standard across many secure websites and applications, enhancing user trust and experience. Implementing this could also reduce the error rate during the registration or login process, where users might mistype their passwords but can't verify this because the characters are hidden.

**Comment by abhijeetnishal** [comment]
Hey @Adeesh-bode, we are redesigning the login/signup #5 
Closing this issue.
