### ISSUE TITLE
Even after login , when the get started button is clicked it redirects to register page

### ISSUE THREAD

**Issue by Adeesh-bode** [abhijeetnishal/Password-Shield#23]
**Is your feature request related to a problem? Please describe.**
Yes, there is a problem where even after users log in, clicking on the 'Get Started' button redirects them to the registration page. This is frustrating because it disrupts the user flow and confuses users who are already logged in but are mistakenly taken to a page meant for new registrations.

**Describe the solution you'd like**
The desired solution is for the 'Get Started' button to intelligently redirect logged-in users directly to their dashboard or the main user interface, rather than the registration page. This would ensure a smooth transition and more intuitive navigation for returning users.

**Describe alternatives you've considered**
As an alternative, the 'Get Started' button could be conditionally rendered based on the user's login status. If the user is logged in, the button could either be hidden or changed to say something like "Go to Dashboard". This makes the user's next steps clearer and avoids unnecessary confusion.

**Additional context**
This issue may lead to user frustration or even users doubting the security or functionality of the website, as it seems to forget their login status. Addressing this would improve user satisfaction and trust in the site's navigation logic.

**Comment by abhijeetnishal** [comment]
Hey @Adeesh-bode, I am assigning this issue to you.

**Comment by abhijeetnishal** [comment]
Hey @Adeesh-bode, what the progress regarding this isssue?

**Comment by KEERTHISOMASI** [comment]
hey @abhijeetnishal i am interested to resolve it

**Comment by abhijeetnishal** [comment]
Hey @KEERTHISOMASI, i am assigning this issue to you now

**Comment by abhijeetnishal** [comment]
I have fixed this issue because it's important and can't be hold. Also i have given more than the required time to finish.
Closing this issue as completed.
