### ISSUE TITLE
Adding Contact us page

### ISSUE THREAD

**Issue by Adeesh-bode** [abhijeetnishal/Password-Shield#24]
**Is your feature request related to a problem? Please describe.**
Currently, our website lacks a dedicated 'Contact Us' page. This omission can leave visitors feeling frustrated and unsupported, as they have no clear or direct way to reach out with questions, feedback, or concerns. Users often expect to find a straightforward method to communicate with site administrators or customer service.

**Describe the solution you'd like**
I would like to see a comprehensive 'Contact Us' page added to the website. This page should include multiple contact options such as a form to fill out, email addresses, phone numbers, and perhaps links to social media. The page should be easily accessible, preferably from the main menu or footer of the site.

**Describe alternatives you've considered**
An alternative to a full page might be a pop-up contact form accessible from all pages via a floating button. This could provide quick access without navigating away from the current page, maintaining user engagement while still offering direct communication options.

**Additional context**
Adding a 'Contact Us' page would not only improve customer support and satisfaction but also enhance the professional appearance of the website. It’s an essential feature for fostering a trustworthy relationship with users and addressing their needs promptly and efficiently.

**Comment by abhijeetnishal** [comment]
Do you have any UI for contact us page?

**Comment by Tanishka023** [comment]
Hey there! I am excited to contribute to this project; please assign it to me.

**Comment by abhijeetnishal** [comment]
Hey @Tanishka023, do you have any UI reference or how you are solving this issue?

**Comment by Tanishka023** [comment]
> Hey @Tanishka023, do you have any UI reference or how you are solving this issue?
> 

![Screenshot_2024-05-12-14-01-10-59_6012fa4d4ddec268fc5c7112cbb265e7.jpg](https://github.com/abhijeetnishal/Password-Shield/assets/120386924/89d109ee-2b13-4fe8-b965-e67fdec82889)

How is this? I worked on this recently. @abhijeetnishal

**Comment by abhijeetnishal** [comment]
Hey @Tanishka023, this UI doesn't matches with our project. Do you have any other designs from figma or any other sources.
This UI doesn't matches with website primary color (brand color) and have think about the what happens on clicking submit button?

**Comment by Tanishka023** [comment]
> Hey @Tanishka023, this UI doesn't matches with our project. Do you have any other designs from figma or any other sources.
> This UI doesn't matches with website primary color (brand color) and have think about the what happens on clicking submit button?

@abhijeetnishal the color can be fixed easily.

**Comment by abhijeetnishal** [comment]
Ok then it's fine @Tanishka023. 
some suggesion:
1. Follow the primary color we are using currently for our website. 
2. Use **Tailwind CSS** for styling
3. The UI should be responsive

I am assigning this issue to you now.

**Comment by abhijeetnishal** [comment]
Hey @Tanishka023, what's the progress? Are you working on this issue?

**Comment by Tanishka023** [comment]
> Hey @Tanishka023, what's the progress? Are you working on this issue?

Yes sir, on it! @abhijeetnishal

**Comment by mtg718** [comment]
Hi, @abhijeetnishal please assign this issue to me under GSSoc'24.

**Comment by abhijeetnishal** [comment]
Hey @mtg718, @Tanishka023 is already working on this issue. Work on other issues or project, good luck.

**Comment by abhijeetnishal** [comment]
Closing this issue as done.
