### ISSUE TITLE
Unable to save passwords in Password-Shield.

### ISSUE THREAD

**Issue by abhiperfect** [abhijeetnishal/Password-Shield#27]
**Describe the bug**
Unable to save passwords in Password-Shield.

**To Reproduce**
1. Go to 'After Login, go to Key Safe'.
2. Click on 'Add New'.
3. See the error message: 'You haven't saved any passwords.'

**Expected behavior**
Passwords should be saved and displayed.

**Screenshots**

https://github.com/abhijeetnishal/Password-Shield/assets/114478676/3adc7663-9e82-401c-8e06-2fa34f4a6b4a

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser: [e.g. Chrome, Firefox]
 - Version: [e.g. 89.0.4389.90]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 12]
 - OS: [e.g. iOS 14]
 - Browser: [e.g. Safari, Chrome]
 - Version: [e.g. 14.4.2]

**Comment by abhiperfect** [comment]
Subject: Urgent: Bug Report - Unable to Save Passwords in Password-Shield

Hello @abhijeetnishal   ,

I hope this message finds you well. I've encountered a critical issue with the Password-Shield application that requires immediate attention.

**Bug Description:**
Users are unable to save passwords in Password-Shield. Upon attempting to add a new password, an error message is displayed stating, "You haven't saved any passwords."

Could you please Assign me this task so i can handle it.

Best regards,
Abhishek

**Comment by abhijeetnishal** [comment]
Hey @abhiperfect, thanks for finding this bug. I am assigning this issue to you now.

**Comment by abhijeetnishal** [comment]
Hey @abhiperfect, if possible could you please fix this issue little early so that i can review and merge because many contributers facing issues.

**Comment by abhiperfect** [comment]
give me some time, i am working on it.

**Comment by abhiperfect** [comment]
@abhijeetnishal sir please authorize the pull request.

**Comment by abhijeetnishal** [comment]
Hey @abhiperfect, you don't need approval for pull request. You are making PR from your forked repo?

**Comment by abhijeetnishal** [comment]
Hey @abhiperfect, i will review and let you know

**Comment by abhijeetnishal** [comment]
Hey @abhiperfect, Good job, i have merged this issue.
I am closing this issue now.
