### ISSUE TITLE
Feat: UI can be imporved and Dark and Light Mode

### ISSUE THREAD

**Issue by mukulpythondev** [abhijeetnishal/Password-Shield#29]
**Describe the solution you'd like**
 -  Light and Dark Mode can be implemented. 
  -  The buttons having not the hovering effect and the getting  unneccessary scrollbar on login page and many more.

**Comment by abhijeetnishal** [comment]
Hey @mukulpythondev, there is some other UI changes are there after that we need to implement these features.

**Comment by mukulpythondev** [comment]
Thanks I will wait
