### ISSUE TITLE
[feature] Server side search feature

### ISSUE THREAD

**Issue by abhijeetnishal** [abhijeetnishal/Password-Shield#3]
- Implement search functionality (server side)
- Search query should based on website name
- Request URL should looks like: api/get?query=am&limit=10&...
- Response should return an list according to searched result.

**Comment by Sakshamag21** [comment]
Hi @abhijeetnishal   I would like to work on this issue for GSSOC'24 and all other issues as well. I am attaching my resume for reference of my work. [https://drive.google.com/file/d/1HgwfbdcNRL-e9LTkqVRpu3XAbmMK8faf/view?usp=sharing](resume) . My discord id:- 210906_sakshamagarwal

**Comment by Sushil642** [comment]
Hi @abhijeetnishal plz assign this issue to me.I would like to work on this issue.
Also i am getting problem during registration . I think there is problem in deployment server.

**Comment by abhijeetnishal** [comment]
> Hi @abhijeetnishal I would like to work on this issue for GSSOC'24 and all other issues as well. I am attaching my resume for reference of my work. [https://drive.google.com/file/d/1HgwfbdcNRL-e9LTkqVRpu3XAbmMK8faf/view?usp=sharing](resume) . My discord id:- 210906_sakshamagarwal

Hey @Sakshamag21, I already assign #4 work on that.

**Comment by abhijeetnishal** [comment]
> Hi @abhijeetnishal plz assign this issue to me.I would like to work on this issue. Also i am getting problem during registration . I think there is problem in deployment server.

Hey @Sushil642, I am assigning this issue to you. Good luck.

**Comment by abhijeetnishal** [comment]
Hey @Sushil642, what's the progress in this issue?

**Comment by HARISH-1222** [comment]
Yep.. 👍

**Comment by HARISH-1222** [comment]
Hi @abhijeetnishal 👋

in which router file you like to implement the api/get?query=am&limit=10&...

either URL or user ?

**Comment by abhijeetnishal** [comment]
> Hi @abhijeetnishal 👋
> 
> in which router file you like to implement the api/get?query=am&limit=10&...
> 
> either URL or user ?

I think password route 😅 come back to this repo

**Comment by abhijeetnishal** [comment]
Use the same get passwords api and inside controller implement search with query, limit, etc

**Comment by HARISH-1222** [comment]
sorry bro 😂

**Comment by HARISH-1222** [comment]
Hello @abhijeetnishal 👋

when i working on this I saw that 
we can able to save the password with the same website name

is it ok?

**Comment by abhijeetnishal** [comment]
> Hello @abhijeetnishal 👋
> 
> when i working on this I saw that we can able to save the password with the same website name
> 
> is it ok?

Yes @HARISH-1222, this is possible. Users may have 2 account for same website e.g. Google accounts
I am updating schema to add title and description also then they can differentiate
