### ISSUE TITLE
Implementing the password validation on client side to make strong password.

### ISSUE THREAD

**Issue by Abhinavhaldiya** [abhijeetnishal/Password-Shield#30]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Problem:
User can enter password of any length and anything it is acceptable.
Solution:
Implementing the password validation checks on frontend while user tries to signup such as the password must be of 8 length,contains atleast one special character and a number.If the user matches all the password checks then,user can be successfully registered.
Idea to solve:
Use a zod library and create a REGEX for password to check the necessary conditions and then parse the password from that zod schema.

Hiii @abhijeetnishal please look towards it. Hoping for your feedback.

**Comment by abhijeetnishal** [comment]
Hey @Abhinavhaldiya, this can be done after issue #5

**Comment by Abhinavhaldiya** [comment]
> Hey @Abhinavhaldiya, this can be done after issue #5

Okay
