### ISSUE TITLE
Adding a confirm password field while adding a new password.

### ISSUE THREAD

**Issue by Abhinavhaldiya** [abhijeetnishal/Password-Shield#31]
Problem:
User needs to enter the password twice as to keep it  always correct.If user by mistake entered wrong password and forgets to recheck and after sometime he/she tries to see on the web then, he will eventually find it something else.

Solution:
Implement it by creating two password fields.

**Comment by abhijeetnishal** [comment]
Hey @Abhinavhaldiya, this issue and previous both one can be done after issue #5 in single issue

**Comment by abhijeetnishal** [comment]
Closing this issue as duplicate.
