### ISSUE TITLE
While editing saved password old data is not there

### ISSUE THREAD

**Issue by Saksham1411** [abhijeetnishal/Password-Shield#33]
**Describe the bug**
When we click on the edit password button the pop-up comes with empty fields. 

**Expected behavior**
It has to come with old data like the website name.
to make it easy for users to update passwords and enhance their user experience

**Screenshots**
![Screenshot 2024-05-13 103649](https://github.com/abhijeetnishal/Password-Shield/assets/101385720/ebb1b6d7-bef8-4e6c-9c11-ecc9790f3421)
Showing empty fields

**Comment by Saksham1411** [comment]
As a GSsoc'24 contributor. I want to address this issue. I request you to assign this to me @abhijeetnishal

**Comment by abhijeetnishal** [comment]
Hey @Saksham1411, i am assigning this issue to you now.

**Comment by abhijeetnishal** [comment]
Issue fixed #4
