### ISSUE TITLE
Enhance your Navbar

### ISSUE THREAD

**Issue by harshmishra19** [abhijeetnishal/Password-Shield#34]
**Is your feature request related to a problem? Please describe.**

The current navbar lacks icons, which impacts its visual appeal and usability. Users might find it less engaging and intuitive to navigate through the website without visual cues provided by icons.

**Describe the solution you'd like**

I propose adding some more options and respective icons to the navbar to enhance its visual appeal and improve user navigation experience. These icons will align with the theme of the website and provide users with clear visual cues for each navigation option

**Describe alternatives you've considered**

One alternative could be redesigning the navbar layout or color scheme. However, adding icons is a more direct and effective solution to address the visual appeal and usability concerns of the navbar

**Additional context**

![Screenshot 2024-05-11 080754](https://github.com/abhijeetnishal/Password-Shield/assets/115486960/c1b6ba4a-441a-4379-ab22-0c24447e32f7)
![Screenshot 2024-05-12 083752](https://github.com/abhijeetnishal/Password-Shield/assets/115486960/787adaad-2ff6-407e-8280-77a0aa4873b4)

**Comment by abhijeetnishal** [comment]
Hey @harshmishra19, we don't have much tabs now so we don't need navbar for now.
