### ISSUE TITLE
Buttons can be designed to look better

### ISSUE THREAD

**Issue by Rakshit-gen** [abhijeetnishal/Password-Shield#37]
**Is your feature request related to a problem? Please describe.**
Buttons on the website are really simple and non reactive.

**Describe the solution you'd like**
We can add some hover and focus effects on the buttons to improve the overall UI of the website

**Comment by abhijeetnishal** [comment]
Hey @Rakshit-gen, there are some changes required for this project.
So i am closing this issue now.
