### ISSUE TITLE
[Feature] : Logout alerting screen

### ISSUE THREAD

**Issue by sivaprasath2004** [abhijeetnishal/Password-Shield#38]
**Is your feature request related to a problem? Please describe.**
- If the user can be `click` the automatically logout.
- Confimation to `logout`  option is the best user-friendly accessable.

**Describe the solution you'd like**
- If you want to logout  click `continue` or `cancel` this is can be important in this project.

**Comment by abhijeetnishal** [comment]
Hey @sivaprasath2004, do you have any reference UI for this that you are planning to implement

**Comment by sivaprasath2004** [comment]
@abhijeetnishal yes. I have a planned please assign me

**Comment by Vanshitgupta9717** [comment]
Hey @Adeesh-bode, I am assigning this issue to you.

**Comment by Vanshitgupta9717** [comment]
Hey @sivaprasath2004, I am assigning this issue to you.

**Comment by Riyasharma1311** [comment]
@abhijeetnishal please assign me this . I want to contribute on this

**Comment by abhijeetnishal** [comment]
> @abhijeetnishal yes. I have a planned please assign me

Hey @sivaprasath2004, you haven't shared the UI so that I can check it matches with our project or not

**Comment by abhijeetnishal** [comment]
I guess no one is working on this, closing this issue.
