### ISSUE TITLE
Filter genuine email

### ISSUE THREAD

**Issue by pankaj-bind** [abhijeetnishal/Password-Shield#39]
**Is your feature request related to a problem? Please describe.**
In your application anyone can enter using **temporary or disposable email** for login.

**Describe the solution you'd like**
I will add a feature so that no one could create an account using **temporary or disposable email**.
It will allow only genuine users in your database.
It will help to avoid any bot.

**Additional context**
Assign me this work under GSSoC24, I will implement it.

**Comment by abhijeetnishal** [comment]
Hey @pankaj-bind, how will you implementing this feature, could you explain?

**Comment by pankaj-bind** [comment]
I will use an API which is free it will first checks is the email genuine or not, if yes then it proceed otherwise, breaks operation and shows a popup "invalid email"
I have tried this

**Comment by abhijeetnishal** [comment]
Hey @pankaj-bind, thanks for sharing your approach but I think that service has some rate limit as it's free, could you share the service you are planning to use which you described.

**Comment by pankaj-bind** [comment]
> Hey @pankaj-bind, thanks for sharing your approach but I think that service has some rate limit as it's free, could you share the service you are planning to use which you described.

It doesn't have any limit

**Comment by abhijeetnishal** [comment]
Ok then I am assigning this issue to you know
