### ISSUE TITLE
[Feature] Client side search 

### ISSUE THREAD

**Issue by abhijeetnishal** [abhijeetnishal/Password-Shield#4]
#3 Server side implementation issue

### Requirements:
- Share the reference UI for search input before implementing
- Search query should be present in URL query params 
- Use Debouncing for search
- UI should be responsive

**Comment by abhijeetnishal** [comment]
Hey, @Sakshamag21, I am assigning this issue to you. Good luck.

You don't need to share your resume to assign issue on Github, just ask for project maintainer is the issue is not assigned to anyone.

**Comment by SumitKumar-17** [comment]
@abhijeetnishal I would like to work on the issue .could you assign it to me under GSSOC'24. 
Reference for the feature you asked https://movie-flex-omega.vercel.app/

**Comment by Sakshamag21** [comment]
Hi @abhijeetnishal  in debouncing what is the avg delay that you are expecting and another point is if search  query is presented in the URL then wont there be a case when suppose I copy the URL and access the search without even authorised.

**Comment by abhijeetnishal** [comment]
Hey @Sakshamag21, take average delay of 500ms. 
We are handling the authentication on our backend using JWT and in our backend we have middleware which checks users is valid or not using token if user is not valid or token is not present then the request is rejected and query is not executed.

**Comment by abhijeetnishal** [comment]
Hey @Sakshamag21, what's the progress are you working on this issue

**Comment by Sakshamag21** [comment]
Hi sorry @abhijeetnishal but till now I haven't made any significant progress as I was busy in my project of college as deadline is this Sunday only. But I will make sure that I will provide you with some significant PR by Monday night.

**Comment by abhijeetnishal** [comment]
Ok @Sakshamag21, no problem
