### ISSUE TITLE
FEATURE: PASSWORD LABEL

### ISSUE THREAD

**Issue by Manishak798** [abhijeetnishal/Password-Shield#42]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/abhijeetnishal/Password-Shield/assets/90680330/11b3b347-df67-4da4-a964-d1455a8152eb)

what if as a user I want to label my saved password for eg: this password is of my gmail, this one is for my amazon login and so on. we can consider giving users a choice to name there saved password so they can directly access them.

**Additional context**
I am a **MENTOR** in **GSSoC'24** raising this issue for contributors to contribute.

**Comment by abhijeetnishal** [comment]
This feature looks good, thanks @Manishak798 for adding this issue.

**Comment by Riyasharma1311** [comment]
@abhijeetnishal assign me this issue . It looks interesting to work on

**Comment by abhijeetnishal** [comment]
Hey @Riyasharma1311, I am assigning this issue to you.

**Comment by abhijeetnishal** [comment]
Migrated this issue to #88
