### ISSUE TITLE
feat:Implement reset password

### ISSUE THREAD

**Issue by Niharika0104** [abhijeetnishal/Password-Shield#45]
**Is your feature request related to a problem? Please describe.**
I see that forget password is missing in the application 

**Describe the solution you'd like**
I will implement forget password and add necessary backend code as well as the ui for it

**Comment by abhijeetnishal** [comment]
Hey @Niharika0104 and @Paarisha1, how do you implement this, could you explain the flow, what service you are using, you are implementing for client or server side, etc.

**Comment by Niharika0104** [comment]
When user clicks on forget password then I will redirect them to forget password page which will prompt user for email.If email exists then password reset mail will be sent and confirmation message will shown and if email doesn't exists,then email is not registered this kind of message will be shown.I will use react toast to show the messages.How does this sound to you?

**Comment by abhijeetnishal** [comment]
So you are going to work on frontend side only right?

**Comment by Niharika0104** [comment]
@abhijeetnishal  No I will add necessary routes as well

**Comment by abhijeetnishal** [comment]
So what's your server side logic, what service you are using, what external package, etc. explain.

**Comment by Niharika0104** [comment]
Using node js and express js I will create routes and using nodemailer I will send mails.

**Comment by abhijeetnishal** [comment]
Ok then I will assigning this issue to you.

**Comment by abhijeetnishal** [comment]
I have added this issue as level2 issue so work properly following project guidelines.
Use Tailwind CSS for client side and UI should be responsive and matches our project.
Good luck

**Comment by Niharika0104** [comment]
I will push changes with in 3 days

**Comment by abhijeetnishal** [comment]
> I will push changes with in 3 days

Take time but try to do best solution

**Comment by mtg718** [comment]
Hi, @Durgesh4993 please assign this issue to me under GSSoc'24.

**Comment by Sahilll15** [comment]
@abhijeetnishal  consider reassign

**Comment by nishant0708** [comment]
Hey @abhijeetnishal can I work on this issue if no one is working??

**Comment by abhijeetnishal** [comment]
Hey @nishant0708, i guess @Niharika0104 is working on this issue.

**Comment by nishant0708** [comment]
@abhijeetnishal  It's 3 week since she raised pr ..so I guess she is not working .

**Comment by abhijeetnishal** [comment]
> @abhijeetnishal It's 3 week since she raised pr ..so I guess she is not working .

Hey @nishant0708, even I thought but today she commented in the PR that she is working. She mentioned that it will take 3 more days to finish as she is busy in some other works. 

Hey @Niharika0104 if you are not getting time give this issue to @nishant0708.

**Comment by nishant0708** [comment]
hey  @abhijeetnishal she is not responding  can i work on it now??

**Comment by abhijeetnishal** [comment]
Hey @Niharika0104, are you available?

Hey @nishant0708, wait for some time

**Comment by Niharika0104** [comment]
@abhijeetnishal I have pr ready for that I need to do some changes and will push it within the time frame I mentioned.

**Comment by abhijeetnishal** [comment]
Hey @nishant0708, are you interested on this issue?

**Comment by nishant0708** [comment]
Yes

**Comment by abhijeetnishal** [comment]
Go through the PR I reviewed to know what all things are required.

**Comment by abhijeetnishal** [comment]
Also pull the Changes from ui-fix branch as we changed the UI.

**Comment by nishant0708** [comment]
Okay

**Comment by abhijeetnishal** [comment]
Hey @nishant0708, I have merged all the code to master and it's live now you check and accordingly you can implement.

**Comment by nishant0708** [comment]
Okay I will do it
