### ISSUE TITLE
feat: Add favicon.

### ISSUE THREAD

**Issue by abhiperfect** [abhijeetnishal/Password-Shield#46]
**Is your feature request related to a problem? Please describe.**
Users find it challenging to quickly identify and distinguish websites when multiple tabs are open in a browser. A favicon can help address this issue by providing a visual cue for each website.

**Describe the solution you'd like**
I would like to see a favicon added to the website to enhance its visual identity and make it easier for users to recognize and access it among other tabs.

**Describe alternatives you've considered**
An alternative solution could be improving the website's title or using a unique color scheme for the browser tab, but a favicon would be the most effective and standard solution.

**Additional context**
Favicons are small icons displayed in the browser tab next to the page title. They are a standard feature of web design and greatly contribute to a website's branding and usability.

**Comment by abhiperfect** [comment]
Subject: Request to Assign Favicon Task

Hi @abhijeetnishal  ,

I hope you're doing well. I'm interested in taking on the task of adding a favicon to our website. This small yet impactful addition can significantly enhance user experience and strengthen our brand identity. 

Problem: Users struggle to identify our website among multiple open tabs.
Solution: Adding a favicon provides a visual cue for easier recognition.
Benefits: Improved user experience and enhanced brand representation.

I believe I have the skills and enthusiasm to complete this task efficiently. Could you please assign it to me? I'm open to any guidance you may have.

Thank you for considering my request.



Best,
Abhishek

**Comment by abhijeetnishal** [comment]
Assigning this issue to you.
