### ISSUE TITLE
Fix: Register page is hiding social icons.

### ISSUE THREAD

**Issue by abhiperfect** [abhijeetnishal/Password-Shield#47]
**Describe the bug**
The register page is hiding social icons, making it difficult for users to find and utilize them.

**To Reproduce**
1. Go to the register page.
2. Look for the social icons section.
3. Observe that the social icons are hidden or not visible.
4. Attempt to interact with the hidden icons, resulting in difficulty accessing social login options.

**Expected behavior**
The social icons should be clearly visible and accessible on the register page, allowing users to easily log in using their social accounts.

**Screenshots**
![Screenshot 2024-05-14 123517](https://github.com/abhijeetnishal/Password-Shield/assets/114478676/a96a518b-fd14-466b-946e-785ec0024595)

**Desktop:**
- OS: [e.g. Windows 10]
- Browser: [e.g. Chrome 98.0.4758.102]
- Version: [e.g. 98.0.4758.102]

**Smartphone:**
- Device: [e.g. iPhone 12]
- OS: [e.g. iOS 15.4]
- Browser: [e.g. Safari 15.1]
- Version: [e.g. 15.1]

**Comment by abhijeetnishal** [comment]
Hey @abhiperfect, #5 fixes all these 
Closing this issue as duplicate
