### ISSUE TITLE
[Feature] : Login & Register Form

### ISSUE THREAD

**Issue by sivaprasath2004** [abhijeetnishal/Password-Shield#48]
- If the `login & Register` page design was very normal to change `professinal UI` and New Design..
- I will ready to Implement the New design for `login & Register` this more user-friendly and more UI powerful..
- please assign me..... :eyes: 

[Screencast from 2024-05-13 22-21-50.webm](https://github.com/SamarthKadam/ChatBox/assets/121082414/64cab9a8-d2e1-4f8c-b828-7dd67b3ef7cb)

**Comment by abhijeetnishal** [comment]
Hey @sivaprasath2004, there is an issue #5 where we are changing UI.

You can ask there if that task is not done.

Closing this issue as duplicate.
