### ISSUE TITLE
[FEAT]: Adding Search Functionality  

### ISSUE THREAD

**Issue by HARISH-1222** [abhijeetnishal/Password-Shield#49]
Hi @abhijeetnishal 👋

**Is your feature request related to a problem? Please describe.**
I saw your pagination request #1 So like that we also need a search feature to get the password instead of scrolling top to bottom

**Describe the solution you'd like**
I like the make search functionality based on the website name are #42 Label-based 
and #42 is not still assigned so if you need that feature let me know.

**Additional context**
I Look through your backend code and it is nice
I planned to index the website in DB so that we could get the search results as soon as possible 
what about your idea in retrieving the search result either Index the data are make an elastic search?

Open to your suggestions....😊

If you like, I will be happy to contribute under GSSOC🧑🏻‍💻

**Comment by abhijeetnishal** [comment]
There already exists an issue #3 
We can discuss assignment from issue 3 only.

Closing this issue as duplicate.
