### ISSUE TITLE
The navbar is not fixed in each pages

### ISSUE THREAD

**Issue by Sibam-Paul** [abhijeetnishal/Password-Shield#54]
**Is your feature request related to a problem? Please describe.**
### The navbar is not fixed in each pages

**Describe the solution you'd like**
**navbar need to be fixed on scrolling for user convenience**

**Additional context**
the navbar:
![image](https://github.com/abhijeetnishal/Password-Shield/assets/158052549/91d0d01e-fbd4-448f-9d45-d31b3e58b093)
issue:
![image](https://github.com/abhijeetnishal/Password-Shield/assets/158052549/8c4b08e8-74ce-44ee-bf77-94917af052f8)
Also:- here
![image](https://github.com/abhijeetnishal/Password-Shield/assets/158052549/a09352fe-27bc-4031-9fa6-69eea3e26460)

_Want to want on this issue and assign me this issue under GSSOC'24_

**Comment by KEERTHISOMASI** [comment]
hey can assign this to me

**Comment by devu007** [comment]
Hello, I want to work on this issue as I have experience in this and would love to contribute to this project.

**Comment by abhijeetnishal** [comment]
Hey @Sibam-Paul, we are migrating from react to next.js #51 once it's done, you can work on this
