### ISSUE TITLE
Enhance Readme.md file 

### ISSUE THREAD

**Issue by aasthakourav20** [abhijeetnishal/Password-Shield#56]
Hey @abhijeetnishal , A Readme file plays an important role in User/Contributor convenience . It  is essential in any given repository because it serves as the primary source of information about the project. It provides an overview of the project's purpose, how to install and use it, and any necessary prerequisites. Additionally, the README often includes guidelines for contributing, links to documentation, and contact information for the maintainers. 
Let's create a more descriptive , attention seeking README file including all guidelines .

Kindly assign this issue to me under GSSoC'24 .

**Comment by abhijeetnishal** [comment]
Hey @aasthakourav20, currently readme is fine.
