### ISSUE TITLE
Website is not responsive.

### ISSUE THREAD

**Issue by Shelbybosss** [abhijeetnishal/Password-Shield#57]
I Will Make the UI responsive to mobile devices as well as tablets.

![Screenshot 2024-05-16 193801](https://github.com/abhijeetnishal/Password-Shield/assets/102911609/c26cb713-68b1-4bc7-b2a5-81594e1cff6a)

Assign me this Issue.

**Comment by Shelbybosss** [comment]
@abhijeetnishal Assign me this issue, i will fix it

**Comment by abhijeetnishal** [comment]
Hey @Shelbybosss, we are migrating the code from react to next.js, once this is done then we will think
