### ISSUE TITLE
Feat: Their should link on navbar to see all current user password.

### ISSUE THREAD

**Issue by abhiperfect** [abhijeetnishal/Password-Shield#61]
**Is your feature request related to a problem? Please describe.**
Suppose you've closed your tab, but because your credentials are saved in the browser, you aren't logged out. However, you can't see all your passwords when you open your "key-safe" tab again, because there's no option available. You'd need to log out and log back in to view them all.

**Describe the solution you'd like**
I would like a solution where even if I've closed the tab, I can still access all my saved passwords in the browser without needing to log out and log back in. This could be achieved by providing an option to view all saved passwords directly from the login screen or by implementing a feature that allows access to saved passwords without requiring a fresh login session.

**Comment by abhiperfect** [comment]
I Would like to work on this issue.

**Comment by abhijeetnishal** [comment]
This issue is similar to #23 
Closing this issue as duplicate
