### ISSUE TITLE
Increasing responsiveness and Enhancement of the website

### ISSUE THREAD

**Issue by KeerthiVuppala24** [abhijeetnishal/Password-Shield#63]
Features needed in the project are:
1. Sign In button addition 
2. Enhancing the Navbar
3. Making the website responsive for all the layouts
4. Alignment of header and footer contents in a more effective way
5. Adding further more styling to improve the view of the website. 

I am willing to add these features. I hope I can be assigned through GSSOC. @abhijeetnishal

**Comment by abhijeetnishal** [comment]
Hey currently we changing UI for signup and login #5 and also migrating #51 once done we will work on it

**Comment by KeerthiVuppala24** [comment]
Ok sure. I hope I can be assigned asap.

**Comment by abhijeetnishal** [comment]
Depends on other issues

**Comment by KeerthiVuppala24** [comment]
Ok, thanks.

**Comment by abhijeetnishal** [comment]
Hey @KeerthiVuppala24, now we have redesigned the UI you can check. Dashboard UI is currently not looking good as landing page. If you interested working on this, let me know?

**Comment by KeerthiVuppala24** [comment]
Yes, I'm interested.

**Comment by abhijeetnishal** [comment]
Do you have any UI reference i guess not, so go throw the current landing page and dashboard page and get some design from internet that matches the our project current UI and share with me before implementing.
I am assigning this issue to you.

**Comment by abhijeetnishal** [comment]
Closing this issue as not active.
