### ISSUE TITLE
Adding list of contributors image under readme

### ISSUE THREAD

**Issue by Arpcoder** [abhijeetnishal/Password-Shield#65]
**Describe the solution you'd like**
List of contributors image under readme

**Additional context**
![Screenshot 2024-05-18 124533](https://github.com/abhijeetnishal/Password-Shield/assets/100352419/ec5f4ff2-cbee-400d-a7f9-abeb1f17053a)

**Comment by abhijeetnishal** [comment]
Hey @Arpcoder, currently we don't have much contributers to show. 
My be in future we will add. Contribute to other issues or project, good luck.
