### ISSUE TITLE
feat: Adding a feature for password toggling .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [abhijeetnishal/Password-Shield#66]
**Is your feature request related to a problem? Please describe.**

By giving this feature to the user it will helps the user to hide and show the password .
**Describe the solution you'd like**
Add an eye icon to the password field .

![Screenshot 2024-05-18 203443](https://github.com/abhijeetnishal/Password-Shield/assets/118350936/0c684413-0a70-4909-b512-83563a5e395c)

**Comment by abhijeetnishal** [comment]
Hey @Ayushmaanagarwal1211, there is an issue #5 where we refactoring the UI of login/register page. You can ask for this issue there.
