### ISSUE TITLE
[BUG]: Incorrect Page Redirection

### ISSUE THREAD

**Issue by aryansharma220** [abhijeetnishal/Password-Shield#68]
**Describe the bug**
Even after logging in when user click on the get started button it again asks for registration/login

**To Reproduce**
1. Go to home page
3. Click on login and put credentials
4. Go back to home page
5. click on get started

**Expected behavior**
It should redirect to the passwords page not to login

**Screenshots**
![image](https://github.com/abhijeetnishal/Password-Shield/assets/133234867/440e6168-aaa9-4148-ad43-ee8022a97e8e)

As you can see i am logged in still it is asking to login

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser edge

Please assign it to me under gssoc

**Comment by abhijeetnishal** [comment]
Hey @aryansharma220,  there is an issue #23 exists for this bug.
Contribute to other issues or project, good luck
