### ISSUE TITLE
[Feat] Redesign of Landing page

### ISSUE THREAD

**Issue by Vimall03** [abhijeetnishal/Password-Shield#70]
**Is your feature request related to a problem? Please describe.**
The landing page feels outdated and lacks a modern, stylish design. This impacts user engagement and doesn't reflect the high-quality service we offer.

**Describe the solution you'd like**
I would like to completely redesign the landing page to give it a fresh, modern, and stylish look. This includes updating the layout, typography, color scheme, and imagery to be more appealing and user-friendly. I've created a Figma design that encapsulates this new look and feel.

**Additional context**
I've attached a screenshot of the Figma design for reference. The new design focuses on a clean layout, modern fonts, and a cohesive color palette that aligns with the project. This redesign aims to enhance user experience and engagement on our site.

_Kindly assign me this issue under GSSoC'24_

**Screenshot of the design I have in mind**

![Home](https://github.com/abhijeetnishal/Password-Shield/assets/109758195/730f3ea8-cac6-4181-b9e7-0df7c91b57c1)

**Comment by Vimall03** [comment]
Great, Thankyou @abhijeetnishal

**Comment by Vimall03** [comment]
Hello @abhijeetnishal is there any update on this ?

**Comment by abhijeetnishal** [comment]
Hey @Vimall03, currently migration is not done. I am working on this as i am not getting much time. But once it is done, i will let you know. 
Don't worry this issue will be assigned to you.

**Comment by abhijeetnishal** [comment]
Hey @Vimall03, do you have any other UI reference which is valid for both dark/light mode which also contains some illustrations and looks modern and attractive? If you find any please share.

**Comment by Vimall03** [comment]
@abhijeetnishal  Sure i will let you know

**Comment by Vimall03** [comment]
hey @abhijeetnishal  
This Figma Link has 2 designs. I have tried to edit it to match the scope of the project. Let me know what you think about it. 

https://www.figma.com/design/T5ZB3emjxim4JMAqnGQIsZ/GSSoC-KeySafe?node-id=0-1&t=oKrqm9g2lLbQnBlI-1

If you have any design on your mind, kindly send me. I'd be happy to incorporate it!

**Comment by abhijeetnishal** [comment]
Hey @Vimall03, The second design which has both dark and light mode looks good to me but try to match with our website features and functionality. You can take designs from Figma community also.

**Comment by abhijeetnishal** [comment]
Hey @Vimall03, I have assigned this issue to you, use the design we discussed and fit it according to our project need.
If you planning to design the login and signup page also let me know. I will make this level2.

**Comment by Vimall03** [comment]
Sure @abhijeetnishal  , I'll redesign the login and register pages as well.
Kindly make it level 2.

**Comment by abhijeetnishal** [comment]
Great, take the UI for login and signup that matches the design. Share the design once if possible.

**Comment by Vimall03** [comment]
Definitely, I'll keep you posted.
Thankyou!

**Comment by abhijeetnishal** [comment]
> Definitely, I'll keep you posted. Thankyou!

Great

**Comment by abhijeetnishal** [comment]
Hey @Vimall03, have you started implementing the UI?

**Comment by Vimall03** [comment]
Yes, I've completed everything except for the navbar and footer. I'll update you soon.

**Comment by abhijeetnishal** [comment]
> Yes, I've completed everything except for the navbar and footer. I'll update you soon.

Ok 👍

**Comment by Vimall03** [comment]
Hey @abhijeetnishal 
Im having trouble setting up the postgreSQL inorder to access the dashboard. I dont have prior experience working with it. 

- I am facing SSL issue

![image](https://github.com/abhijeetnishal/Password-Shield/assets/109758195/d6a9dfed-bf67-480e-b563-bac9931eabcd)

I managed to connect the db by commenting the  ```
ssl: { rejectUnauthorized: false }
``` in the config file 

- The console is logging Failed To Fetch when I try to register

![image](https://github.com/abhijeetnishal/Password-Shield/assets/109758195/4ef2d28f-f779-4aaf-8b11-e709a4d40713)

**Comment by abhijeetnishal** [comment]
Hey @Vimall03, You can connect without SSL also.
But if you want to use SSL, just remove this line: `  ssl: { rejectUnauthorized: false },`

The dbConnect code should look like:
```ts
const client = new Client({
  connectionString: connectionString,
});
```
Remove the code changes once done.


You can use render PostgreSQL service also it will easy to integrate

**Comment by Vimall03** [comment]
Oky, I ll try this

**Comment by abhijeetnishal** [comment]
Hey @Vimall03, i saw the design https://urlsrt.vercel.app/8RaVQez for the dashboard, i have some queries regarding this:
1. Are we showing frequently used, if yes then how we will show what's the parameter?
2. Are we showing the password strength on adding the password on add password popup?
3. For account we are showing profile page or something?
4. Are we giving the option to upload icon for respective passwords as in design its showing or we will give some predefined password templates?

Other things look good to me.

**Comment by Vimall03** [comment]
I added “frequently used”, “more…” and account tabs keeping in mind the future scope of the project.


Showing the strength of the password can add a unique touch to the site and I believe we can implement it using simple js

I thought of using a default image for the icons as of now since we can’t upload images to the backend

**Comment by abhijeetnishal** [comment]
> I added “frequently used”, “more…” and account tabs keeping in mind the future scope of the project.
> 
> Showing the strength of the password can add a unique touch to the site and I believe we can implement it using simple js
> 
> I thought of using a default image for the icons as of now since we can’t upload images to the backend

Great. 

Yes we can show password strength feature using JS.

Let's give some custom website templates for now later we will implement upload feature. I have to think and decide CDN's and storage pricing for upload.

**Comment by abhijeetnishal** [comment]
Closing this issue as done.
