### ISSUE TITLE
Don't hide the password when editing it

### ISSUE THREAD

**Issue by vaibhavityagi** [abhijeetnishal/Password-Shield#72]
**Is your feature request related to a problem? Please describe.**
As a user, if I want to edit one of my saved passwords, I should not need to unhide it before editing the password.
It is an unnecessary extra step that makes the user experience bitter.
![image](https://github.com/abhijeetnishal/Password-Shield/assets/78082871/584e8c16-be5c-46ff-a05b-606f5f81b221)

**Describe the solution you'd like**
Remove the eye, and allow the user to directly see the password

**Comment by vaibhavityagi** [comment]
Hey, @abhijeetnishal please assign this issue to me under GSSOC24

**Comment by abhijeetnishal** [comment]
Hey @vaibhavityagi, we are currently migrating the code  as you see the issue #51 after that it will be fixed.
Contribute to other issues or project good luck.
