### ISSUE TITLE
[ BUG ] : Registration Validation needs to be enhanced.

### ISSUE THREAD

**Issue by kshavp** [abhijeetnishal/Password-Shield#75]
**Describe the bug**
The registration validation needs to be enhanced as empty quotes as a name ("") can be entered and validated.

**To Reproduce**
1. Go to [Key Safe](https://passwordshield.vercel.app/register)
2. Register with username "" (empty quotes).
3. Login with the credentials

**Expected behavior**
Refer to the attatched media
![image](https://github.com/abhijeetnishal/Password-Shield/assets/95236968/f13ca809-4205-44c1-b582-a00c8ea4c05b)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version 125

@abhijeetnishal I can fix this issue if assigned.

**Comment by abhijeetnishal** [comment]
The issue #51 fix this issue
Contribute to other issues or projects good luck
