### ISSUE TITLE
Register div is not aligned properly

### ISSUE THREAD

**Issue by YadlaMani** [abhijeetnishal/Password-Shield#76]
**Describe the bug**
when opening register page the the div is not properly alligned

**Screenshots**
![image](https://github.com/abhijeetnishal/Password-Shield/assets/133841094/64286661-5b26-492f-8e19-ec05835cbddf)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by abhijeetnishal** [comment]
The issue #51 fix the problem.
Closing this issue.
