### ISSUE TITLE
Want to add a better in detail How to contribute

### ISSUE THREAD

**Issue by Sibam-Paul** [abhijeetnishal/Password-Shield#86]
**Is your feature request related to a problem? Please describe.**
Want to add a better in detail How to contribute

Want to add this
![image](https://github.com/abhijeetnishal/Password-Shield/assets/158052549/8dcd9175-cced-40c7-8ee1-0782b0b05ac7)

in place of 
![image](https://github.com/abhijeetnishal/Password-Shield/assets/158052549/f4654ae9-7b8d-498b-82a0-b6d97bfd413f)

please assign me this issue under GSSOC'24 as I want to work on it

**Comment by abhijeetnishal** [comment]
Hey @Sibam-Paul, Currently this is not important thing to do. Contribute to other issues or projects, good luck.
