### ISSUE TITLE
Website name not visible after adding the website and password

### ISSUE THREAD

**Issue by vansh-sardana** [abhijeetnishal/Password-Shield#87]
**Describe the bug**
Once we save the password for some website, the password is visible but the website link is not visible

**To Reproduce**
1. Login
2. Click on 'Add new'
3. Enter the website name and the password and click on save.

**Expected behavior**
The website name should be visible and not camouflage with the background.

**Screenshots**
![image](https://github.com/abhijeetnishal/Password-Shield/assets/107904311/872f55dc-a87d-4d0a-9f61-f4c8b1d35c40)
![image](https://github.com/abhijeetnishal/Password-Shield/assets/107904311/7f08ab22-51ab-4975-a03b-13cedea2011b)

**Desktop :**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 125.0.6422.112

**Additional context**
The same issue is with edit password and with add new password.
![image](https://github.com/abhijeetnishal/Password-Shield/assets/107904311/f3f0d375-49e4-4fd6-a0af-39d0258c19dc)

**Comment by vansh-sardana** [comment]
Please assign this issue to me. I would be working on this under GGSOC'24.

**Comment by abhijeetnishal** [comment]
Hey @vansh-sardana, I have checked it's visible.

![Screenshot 2024-05-28 172614](https://github.com/abhijeetnishal/Password-Shield/assets/83833440/35c6a35b-d9fa-472e-85d0-c9388de481a0)

**Comment by vansh-sardana** [comment]
@abhijeetnishal it is using browser default font color. On my laptop as well as on my phone its not being shown.
![image](https://github.com/abhijeetnishal/Password-Shield/assets/107904311/129c7258-fa10-4492-824f-5aa82076b43b)
![WhatsApp Image 2024-05-28 at 23 46 42_d45e7e92](https://github.com/abhijeetnishal/Password-Shield/assets/107904311/a8efe9f1-2a7e-426e-86b0-00a2b5c574ef)

**Comment by abhijeetnishal** [comment]
Hey thanks for noticing it's because of global.css file i fixed this issue just a commenting a code.
