### ISSUE TITLE
Notify to user if his/her password is not strong 

### ISSUE THREAD

**Issue by RoshanAnsy** [abhijeetnishal/Password-Shield#90]
After saving the password on the site, it needs to notify the user:

1.If the password is not strong -> Your password is weak. Please update your password.
Else -> Your password is good to go.

**solution **
we need to verify the user password on server side is that it is strong or not and send the response to client accordly.

Alternatively, when the user enters and saves the password on the site, we can immediately send a notification to the client indicating whether the password is strong or not.

**Comment by schauna7** [comment]
hey i would like to work on this

**Comment by abhijeetnishal** [comment]
Hey @RoshanAnsy and @schauna7, currently we are redesigning the complete UI. After that we can implement this.

**Comment by abhijeetnishal** [comment]
This issue will be fixed by #104
