### ISSUE TITLE
(GSSoC'24) Fixing UI of Login and Signup Pages

### ISSUE THREAD

**Issue by Apurv7777** [abhijeetnishal/Password-Shield#92]
## Problems to be solved :
- Setting title and a favicon.
![image](https://github.com/abhijeetnishal/Password-Shield/assets/65327303/7136ad08-862a-4e56-806f-8a11c68b66ff)

- Adding a dark mode functionality.

- Initially, the eye-icon should have a slash on top, to know the user that the password is hidden, and then would the eyes open , when the password is visible.
![image](https://github.com/abhijeetnishal/Password-Shield/assets/65327303/b9d27271-c3bc-4822-91b8-a6d174e46f9c)
![image](https://github.com/abhijeetnishal/Password-Shield/assets/65327303/c4d6a0ab-1b0b-4dbb-9853-c56dc14abfc6)

**Comment by abhijeetnishal** [comment]
Hey @Apurv7777, currently we are designing the UI check the issue #70 

Closing this issue as duplicate
