### ISSUE TITLE
Implement Google Signup Functionality 

### ISSUE THREAD

**Issue by srivastav2006** [abhijeetnishal/Password-Shield#93]
Users should be able to sign up using their Google tokens for authentication.

This feature enhances user convenience by allowing them to sign up using their Google accounts, reducing the need to remember additional login credentials.

I also want to add eye icon for password visibility and remember me check box to remember the user

![image](https://github.com/abhijeetnishal/Password-Shield/assets/143505484/db19aae7-72c6-46d2-ae1d-55d0d0e27c83)

expected:
![image](https://github.com/abhijeetnishal/Password-Shield/assets/143505484/90566283-516d-42ed-a393-51aa4f8502d5)

**Comment by srivastav2006** [comment]
Okay

**Comment by abhijeetnishal** [comment]
Hey @srivastav2006, we redesigned our website. Could you explain how you are going to implement this?

**Comment by nishant0708** [comment]
hey @abhijeetnishal Can i work on This we can implement this by setting up our project on google developers console and get credential from there to setup google signin button then we have to write some scripts and it will start working i have implemented this many times so i can work on it.

**Comment by abhijeetnishal** [comment]
Hey @nishant0708, are you planning to use some library for this on server side?

**Comment by abhijeetnishal** [comment]
Hey @nishant0708, have you done this without using passport because I am thinking of doing this without using any library as we are already using bigger library like mongoose, nodemailer, etc. I am thinking of doing this using http method by getting access token and then user info and then save to DB. Also it's not difficult to implement this not like email or other features.

**Comment by abhijeetnishal** [comment]
Google one tap is I don't know if you saw that or not, in some websites you will see the Google accounts as popup at top right when clicking it will directly login to that Google account instead of redirecting.

**Comment by abhijeetnishal** [comment]
Closing this issue as not active.
