### ISSUE TITLE
Url validation is not found

### ISSUE THREAD

**Issue by mukilan2815** [abhijeetnishal/Password-Shield#94]
**Describe the bug**
We need to check whether the website is valid or not. Wrong url also accepting.

**To Reproduce**
1. Go to dashboard
2. Click on +Add New
3. See error

**Expected behavior**
The url field is not validating the input. It is accepting all the inputs .

**Screenshots**

![image](https://github.com/abhijeetnishal/Password-Shield/assets/71129858/4e344f14-efa3-4743-86be-31522b8c85f1)

Kindly assign me this issue under GSSOC'24 as a contributor. I would be eager to fix this up.

**Comment by abhijeetnishal** [comment]
It's not necessary to validate URL, let users add for now. 

Contribute to other issues good luck.
