### ISSUE TITLE
When view password icon is clicked , it shows all the passwords without showing that particular password

### ISSUE THREAD

**Issue by mukilan2815** [abhijeetnishal/Password-Shield#95]
**Describe the bug**
When i click that eye icon to view the password , all the passwords in that websites are showing. 

**To Reproduce**
1. Go to 'dashboard'
2. Click on 'View (eye icon)'
3. See error

**Expected behavior**
When user press that eye icon , it should only show the particular password.

**Screenshots**
![image](https://github.com/abhijeetnishal/Password-Shield/assets/71129858/a3261667-d103-41fb-9ed8-29578f2c6867)

**Additional context**
kindly assign me this task under GSSOC'24

**Comment by abhijeetnishal** [comment]
Hey @mukilan2815, this bug is already fixed. i will deploy the changes currently it is not live.
