### ISSUE TITLE
BUG : Incorrect Title on Title Bar

### ISSUE THREAD

**Issue by adityas-github** [abhijeetnishal/Password-Shield#96]
**Describe the bug**
The title displayed in the title bar of the website is incorrect. It does not match the intended title for the page, causing confusion for users and potential SEO issues.

**To Reproduce**
2. Observe the title in the browser's title bar.
3. Compare the title bar text with the expected page title.
4. See error.

**Expected behavior**
The title bar should display the correct title that accurately reflects the content and purpose of the page. Also, I can add meta description to optimize it from an SEO perspective.

**Screenshots**

![image](https://github.com/abhijeetnishal/Password-Shield/assets/98210910/d6da3cd6-68b3-486d-9cf5-24c92c3b47af)

- [x] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC'24 contributor
- [x] I want to work on this issue

**Comment by abhijeetnishal** [comment]
This issue will be fixed by #70 

Contribute to other issues good luck.
