### ISSUE TITLE
[Feature] Adding Custom Scrollbar

### ISSUE THREAD

**Issue by SwanandD121** [abhijeetnishal/Password-Shield#98]
**Description:**
The platform currently lacks the functionality of theme-matching scrollbar which are pivotal for improving user comfort and navigation fluidity. By integrating this feature, I aim to provide users with a smoother and more personalized browsing experience.

I have implemented this feature multiple times in open source as well as personal projects, so please assign this issue to me under GSSoC'24.

**Comment by abhijeetnishal** [comment]
This will be fixed as we are redesigning the website.
Contribute to other issues good luck.
