### ISSUE TITLE
[Bug] Missing Favicon and Title

### ISSUE THREAD

**Issue by SwanandD121** [abhijeetnishal/Password-Shield#99]
**Describe the bug**
Current title is the default Next App title and there is no favicon which dosen't look professional at all.

**Expected behavior**
The favicon should ideally be the logo of the website and the title should be **Password Sheild**.

**Screenshots**
![image](https://github.com/abhijeetnishal/Password-Shield/assets/117746995/ff42a073-821d-4526-9edd-d3a21dfe8b9f)

Please assign me this issue under GSSoC'24.

PS: I can create a personalised logo for the website if this issue is labelled as level 2.

**Comment by abhijeetnishal** [comment]
This is not a bug and can be fixed as we are redesigning the website.
